services:
  nestjs-api:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb-db

  mongodb-db:
    image: mongodb:latest
    ports:
      - "25027:25027"